apiVersion: v1
kind: Service
metadata:
  name: shopping-api-service
spec:
  type: NodePort # for local testing with Minikube
  selector:
    app: shopping-api
  ports:
    - port: 3000 # service port
      targetPort: 3000 # container port
      nodePort: 30007 # exposed port on minikube node
